### ISSUE TITLE
review@0.0.1

### ISSUE THREAD

**Issue by justcppdev** [Altgear/-8-15#1]
![screenshot-github com-2017-10-20-14-47-45-768](https://user-images.githubusercontent.com/26243572/31819895-656db2d4-b5a7-11e7-9d51-451370e0cb98.png)

**Comment by Altgear** [comment]
![default](https://user-images.githubusercontent.com/11339431/31825865-32184aec-b5bc-11e7-8944-88ef47892e18.png)
Почему вы ссылку отметили?
